// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    sendUid: function(_req, _res) {
      var uid;
      uid = _req.param('uid');
      return _res.text('nihao');
    }
  };

}).call(this);

//# sourceMappingURL=UidInsertController.js.map
