// Generated by CoffeeScript 1.8.0
(function() {
  var Player, PlayerBox, name;

  name = 'userReadyStack';

  Player = (function() {
    function Player() {}

    return Player;

  })();

  PlayerBox = (function() {
    function PlayerBox(name) {
      this.name = name;
    }

    PlayerBox.prototype.add = function(_uid) {};

    return PlayerBox;

  })();

  module.exports = {
    getName: function() {
      return name;
    }
  };

}).call(this);

//# sourceMappingURL=userReadyStack.js.map
